# Generated by Django 5.0.4 on 2024-05-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Churn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.CharField(
                default="sample message from churnshield", max_length=250
            ),
            preserve_default=False,
        ),
    ]
